#!/bin/sh

# Script to compile a new s6-rc database from a given source directories
# and create/update the appropriate symlink to point to the new compiled database

# Some variable definitions
DEST="$1"
TIME=$(date +%y%m%d-%R:%S)
NAME="$(basename "$DEST"-"$TIME")"

# Start compiling the new database
shift
s6-rc-compile "$DEST"-"$TIME" "$@"

# Create/update the symlink
ln -sf "$NAME" "$DEST"
